### ISSUE TITLE
Supported?

### ISSUE THREAD

**Issue by wwahammy** [dwkoogt/pika_que#1]
Hey, I just stumbled on this gem. It looks really great!

I was wondering if this gem is still being supported/developed. There hasn't been any new development in well over a year so I wanted to know what the plans are.

Don't worry, I totally understand that it's open source so there's no formal support but I was hoping to have a better sense of what the future of gem is.

**Comment by dwkoogt** [comment]
Hi, sorry about late response. I didn't see this until today.
Congrats on being the first one to open the issue. 🎉
As of now, there's no plan unless there's more demand for it.
I can do some gem upgrades and cut a release if that's what you require.

**Comment by wwahammy** [comment]
Thanks for getting back to me. I don't have any immediate requirements but updates wouldn't hurt!

I'm mostly just trying to get a sense of your goals so I can set my expectations properly. Not sure yet on whether I'm going to use pika_que or not but your response is very helpful! Thanks for that and for the amazing work you've done!

**Comment by wwahammy** [comment]
@dwkoogt quick question: is this code used in production anywhere that you know of?

**Comment by dwkoogt** [comment]
Hi, sorry again for late response. I checkin only when i need to file issues.
I currently have no plans to actively work on this as no issues have been filed.
I don't know if anybody is using this in production but you can check number of downloads at [rubygems](https://rubygems.org/gems/pika_que/versions/0.2.0).
